Cabal-Version:       3.8
Name:                tiger
Version:             1.0
License:             CC0-1.0
Author:              TheBizzle
Maintainer:          TheBizzle
Homepage:            https://github.com/TheBizzle
Category:            Web
Synopsis:            An implementation of the Tiger programming language
Description:         An implementation of the Tiger programming language, from Andrew W. Appel's Modern Compiler Implementation in ML
Stability:           Experimental
Build-type:          Simple

Source-Repository head
  type:     git
  location: https://github.com/TheBizzle/Tiger.git

Common common
  Default-Language:   GHC2024
  Default-Extensions: OverloadedRecordDot, OverloadedStrings
  Build-Depends:
    bizzlelude >= 4.20.2.0.2 && < 4.21,
  GHC-Options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-import-lists
    -Wredundant-constraints
    -fno-warn-name-shadowing
    -funbox-strict-fields
    -O2

Executable tiger
  Import:          common
  Hs-Source-Dirs:  app
  Main-Is:         Main.hs
  Build-Depends:
    tiger,
    text,

Library
  Import:          common
  Hs-Source-Dirs:  src/main
  Build-Tool-Depends:
    alex:alex   >= 3.5.4 && < 3.6,
    happy:happy >= 2.1   && < 2.2
  Exposed-Modules:
    Tiger.Compiler
    Tiger.Lexer.Lexer
    Tiger.Lexer.Token
    Tiger.Parser.AST
    Tiger.Parser.Parser
    Tiger.Parser.ParserError
  Other-Modules:
    Tiger.Lexer.Internal.Grammar
    Tiger.Lexer.Internal.Lexer
    Tiger.Lexer.Internal.Token
    Tiger.Parser.Internal.AST
    Tiger.Parser.Internal.Happy
    Tiger.Parser.Internal.Parser
    Tiger.Parser.Internal.ParserError
  Build-Depends:
    array        >= 0.5.8 && < 0.6,
    happy-lib    >= 2.1   && < 2.2,
    mtl          >= 2.3.1 && < 2.4,
    text         >= 2.1.3 && < 2.2,
    transformers >= 0.6.1 && < 0.7

test-suite tests
  Import:         common
  Type:           exitcode-stdio-1.0
  Main-Is:        Main.hs
  Hs-Source-Dirs: src/test
  Build-Depends:
    directory   >= 1.3.8  && < 1.4,
    filepath    >= 1.5.4  && < 1.6,
    tasty       >= 1.5.3  && < 1.6,
    tasty-hunit >= 0.10.2 && < 0.11,
    text,
    tiger,
